# Generated by Django 4.2.13 on 2025-11-12 05:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("is_revoked", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_token",
                        to="authentication.refreshtoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "refresh_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMFA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(db_index=True, default=False)),
                ("is_enforced", models.BooleanField(default=False)),
                (
                    "primary_method",
                    models.CharField(
                        choices=[
                            ("totp", "TOTP (Google Authenticator)"),
                            ("sms", "SMS OTP"),
                            ("email", "Email OTP"),
                        ],
                        default="totp",
                        max_length=20,
                    ),
                ),
                ("totp_secret", models.CharField(blank=True, max_length=100)),
                ("totp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("sms_phone", models.CharField(blank=True, max_length=20)),
                ("sms_verified_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "backup_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text="10 one-time use backup codes",
                        size=None,
                    ),
                ),
                (
                    "backup_codes_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "trusted_device_fingerprints",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("total_verifications", models.IntegerField(default=0)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User MFA",
                "verbose_name_plural": "User MFA",
                "db_table": "user_mfa",
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10)),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("login", "Login Verification"),
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                            ("phone_verification", "Phone Verification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("delivery_method", models.CharField(max_length=20)),
                ("delivery_address", models.CharField(max_length=255)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otp_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(db_index=True, max_length=500, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "blacklisted_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("suspicious", "Suspicious"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("logout_at", models.DateTimeField(blank=True, null=True)),
                ("device_type", models.CharField(max_length=50)),
                ("device_brand", models.CharField(blank=True, max_length=100)),
                ("device_model", models.CharField(blank=True, max_length=100)),
                ("device_name", models.CharField(max_length=255)),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField()),
                ("country", models.CharField(blank=True, max_length=100)),
                ("country_code", models.CharField(blank=True, max_length=10)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_trusted", models.BooleanField(default=False)),
                ("is_suspicious", models.BooleanField(db_index=True, default=False)),
                ("trust_score", models.IntegerField(default=50)),
                (
                    "risk_factors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("login_method", models.CharField(default="password", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "refresh_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="authentication.refreshtoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-last_activity"],
                        name="user_sessio_user_id_6a99d2_idx",
                    ),
                    models.Index(
                        fields=["device_fingerprint", "-created_at"],
                        name="user_sessio_device__9c5c40_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("authorization", "Authorization"),
                            ("data_access", "Data Access"),
                            ("data_modification", "Data Modification"),
                            ("system_config", "System Configuration"),
                            ("security", "Security Event"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("token_refresh", "Token Refresh"),
                            ("token_revoked", "Token Revoked"),
                            ("session_expired", "Session Expired"),
                            ("password_changed", "Password Changed"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("password_reset_completed", "Password Reset Completed"),
                            ("password_failed_attempts", "Password Failed Attempts"),
                            ("mfa_enabled", "MFA Enabled"),
                            ("mfa_disabled", "MFA Disabled"),
                            ("mfa_verified", "MFA Verified"),
                            ("mfa_failed", "MFA Failed"),
                            ("backup_code_used", "Backup Code Used"),
                            ("permission_granted", "Permission Granted"),
                            ("permission_revoked", "Permission Revoked"),
                            ("permission_denied", "Permission Denied"),
                            ("role_assigned", "Role Assigned"),
                            ("role_removed", "Role Removed"),
                            ("role_created", "Role Created"),
                            ("role_deleted", "Role Deleted"),
                            ("data_viewed", "Data Viewed"),
                            ("data_exported", "Data Exported"),
                            ("report_generated", "Report Generated"),
                            ("bulk_operation", "Bulk Operation"),
                            ("data_created", "Data Created"),
                            ("data_updated", "Data Updated"),
                            ("data_deleted", "Data Deleted"),
                            ("data_restored", "Data Restored"),
                            ("config_changed", "Configuration Changed"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deactivated", "User Deactivated"),
                            ("user_activated", "User Activated"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("invalid_token", "Invalid Token"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("geolocation_blocked", "Geolocation Blocked"),
                            ("device_changed", "Device Changed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(max_length=255)),
                ("user_role", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField()),
                ("request_method", models.CharField(max_length=10)),
                ("request_path", models.CharField(max_length=500)),
                ("request_query", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("country_code", models.CharField(blank=True, max_length=10)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("device_brand", models.CharField(blank=True, max_length=100)),
                ("device_model", models.CharField(blank=True, max_length=100)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("resource_name", models.CharField(blank=True, max_length=255)),
                ("action", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("is_suspicious", models.BooleanField(db_index=True, default=False)),
                ("risk_score", models.IntegerField(default=0)),
                ("flagged_for_review", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("database_queries", models.IntegerField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type", "-created_at"],
                        name="security_au_user_id_482647_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="security_au_categor_0b0606_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="security_au_ip_addr_2d9366_idx",
                    ),
                    models.Index(
                        fields=["success", "-created_at"],
                        name="security_au_success_11c2d9_idx",
                    ),
                    models.Index(
                        fields=["is_suspicious", "-created_at"],
                        name="security_au_is_susp_b1de7e_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "event_type"],
                        name="security_au_created_87da79_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["token", "is_revoked"], name="refresh_tok_token_0bd5a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["user", "is_revoked"], name="refresh_tok_user_id_893d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["user", "code_type", "-created_at"],
                name="otp_codes_user_id_073692_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["code", "is_used"], name="otp_codes_code_b3c4d3_idx"
            ),
        ),
    ]
